[workspace]
authors = ["Marco Barnfield <mbarnfield63@gmail.com>"]
channels = ["pytorch", "nvidia", "conda-forge", "main", "r", "msys2"]
name = "ML"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
pip = "*"
jupyterlab = "*"
notebook = "*"
ipykernel = "*"
pandas = "*"
numpy = "*"
scipy = "*"
scikit-learn = "*"
statsmodels = "*"
h5py = "*"
matplotlib = "*"
seaborn = "*"
pytorch = "*"
torchvision = "*"
torchaudio = "*"
keras = "*"
pytorch-cuda = "11.8.*"
mpi4py = "*"
tqdm = "*"
requests = "*"

[pypi-dependencies]
adjusttext = "*"
triton = "*"